class Item:
	def __init__(self, name, dropname, category, imagename, artname):
		self.name = name # Name of item, including name to put in the report
		self.dropname = dropname # Name of item used in logs - often omits the ending (e.g. omits 'Orb' or 'Seed')
		self.category = category # Row ID used in logs
		self.imagename = imagename # Image of item sprite
		self.artname = artname # Image of item artwork
		self.floordrops = []
		self.shopdrops = []
		self.tiledrops = []
		self.walldrops = []
		self.dungeonenddrops = []
		self.otherdrops = []
		if dropname == "": # If no drop name specified, use the provided name instead. This allows me to not have to rewrite all 100 TM names
			self.dropname = name

# Loads hardcoded information on items into a list and returns that list
def loadItems():
	itemlist = []
	# Consumables - Food
	itemlist.append(Item("Apple", "Apple", "Consumables", "apple", "Item_image_FOOD_NORMAL"))
	itemlist.append(Item("Big Apple", "Big Apple", "Consumables", "bigapple", "Item_image_FOOD_LARGE"))
	itemlist.append(Item("Chestnut", "Chestnut", "Consumables", "chestnut", "Item_image_FOOD_IGAGURI"))
	itemlist.append(Item("Grimy Food", "Grimy Food", "Consumables", "grimyfood", "Item_image_FOOD_BETOBETA"))
	itemlist.append(Item("Perfect Apple", "Perfect Apple", "Consumables", "perfectapple", "Item_image_FOOD_LARGE_2"))
	itemlist.append(Item("Tiny Apple", "Tiny Apple", "Consumables", "tinyapple", "Item_image_FOOD_SMALL"))

	# Consumables - Stat Up + Recovery
	itemlist.append(Item("Accuracy Drink", "Accuracy Drink", "Consumables", "bluedrink", "Item_image_PARAMETER_WAZA_ACCURACY"))
	itemlist.append(Item("Calcium", "Calcium", "Consumables", "calcium", "Item_image_PARAMETER_S_ATTACK"))
	itemlist.append(Item("Carbos", "Carbos", "Consumables", "carbos", "Item_image_PARAMETER_SPEED"))
	itemlist.append(Item("Iron", "Iron", "Consumables", "iron", "Item_image_PARAMETER_DEFENCE"))
	itemlist.append(Item("Max Elixir", "Max Elixir", "Consumables", "greenbottle", "Item_image_PP_PPMAX"))
	itemlist.append(Item("Max Ether", "Max Ether", "Consumables", "bluedrink", "Item_image_PP_PPAIDER"))
	itemlist.append(Item("Power Drink", "Power Drink", "Consumables", "powerdrink", "Item_image_PARAMETER_WAZA_POWER"))
	itemlist.append(Item("PP-Up Drink", "PP-Up Drink", "Consumables", "pp-updrink", "Item_image_PARAMETER_WAZA_PP"))
	itemlist.append(Item("Protein", "Protein", "Consumables", "protein", "Item_image_PARAMETER_ATTACK"))
	itemlist.append(Item("Zinc", "Zinc", "Consumables", "zinc", "Item_image_PARAMETER_S_DEFENCE"))

	# Berries
	itemlist.append(Item("Cheri Berry", "Cheri", "Berries", "cheriberry", "Item_image_SEED_KURABO"))
	itemlist.append(Item("Chesto Berry", "Chesto", "Berries", "chestoberry", "Item_image_SEED_KAGO"))
	itemlist.append(Item("Oran Berry", "Oran", "Berries", "oranberry", "Item_image_SEED_OREN"))
	itemlist.append(Item("Pecha Berry", "Pecha", "Berries", "pechaberry", "Item_image_SEED_MOMON"))
	itemlist.append(Item("Rawst Berry", "Rawst", "Berries", "rawstberry", "Item_image_SEED_CHIIGO"))
	itemlist.append(Item("Sitrus Berry", "Sitrus", "Berries", "sitrusberry", "Item_image_PARAMETER_OBON"))

	# Projectiles
	itemlist.append(Item("Cacnea Spike", "Cacnea Spike", "Projectiles", "greenspike", "Item_image_ARROW_SABONEA"))
	itemlist.append(Item("Corsola Twig", "Corsola Twig", "Projectiles", "purplespike", "Item_image_ARROW_SANIIGO"))
	itemlist.append(Item("Geo Pebble", "Geo Pebble", "Projectiles", "geopebble", "Item_image_STONE_ISHINOTSUBUTE"))
	itemlist.append(Item("Golden Fossil", "Golden Fossil", "Projectiles", "goldenfossil", "Item_image_STONE_OUGON"))
	itemlist.append(Item("Golden Spike", "Golden Spike", "Projectiles", "goldenspike", "Item_image_ARROW_OUGON"))
	itemlist.append(Item("Gravelerock", "Gravelerock", "Projectiles", "gravelerock", "Item_image_STONE_GOROON"))
	itemlist.append(Item("Iron Spike", "Iron Spike", "Projectiles", "ironspike", "Item_image_ARROW_IRON"))
	itemlist.append(Item("Silver Spike", "Silver Spike", "Projectiles", "silverspike", "Item_image_ARROW_SILVER"))

	# Seeds
	itemlist.append(Item("Ban Seed", "Ban", "Seeds", "seed", "Item_image_SEED_KINSHI"))
	itemlist.append(Item("Blast Seed", "Blast", "Seeds", "seed", "Item_image_SEED_BLAST"))
	itemlist.append(Item("Blinker Seed", "Blinker", "Seeds", "seed", "Item_image_SEED_BLIND"))
	itemlist.append(Item("Decoy Seed", "Decoy", "Seeds", "seed", "Item_image_SEED_OTORI"))
	itemlist.append(Item("Doom Seed", "Doom", "Seeds", "seed", "Item_image_SEED_LV_DOWN"))
	itemlist.append(Item("Empowerment Seed", "Empowerment", "Seeds", "seed", "Item_image_SEED_MEGA"))
	itemlist.append(Item("Energy Seed", "Energy", "Seeds", "seed", "Item_image_SEED_GENKI"))
	itemlist.append(Item("Eyedrop Seed", "Eyedrop", "Seeds", "seed", "Item_image_SEED_MEGUSURI"))
	itemlist.append(Item("Heal Seed", "Heal", "Seeds", "seed", "Item_image_SEED_HEAL"))
	itemlist.append(Item("Joy Seed", "Joy", "Seeds", "seed", "Item_image_SEED_LV_UP"))
	itemlist.append(Item("Life Seed", "Life", "Seeds", "seed", "Item_image_PARAMETER_HP"))
	itemlist.append(Item("Plain Seed", "Plain", "Seeds", "seed", "Item_image_SEED_NORMAL"))
	itemlist.append(Item("Pure Seed", "Pure", "Seeds", "seed", "Item_image_SEED_PURE"))
	itemlist.append(Item("Quick Seed", "Quick", "Seeds", "seed", "Item_image_SEED_QUICK"))
	itemlist.append(Item("Reviver Seed", "Reviver", "Seeds", "seed", "Item_image_SEED_FUKKATSU_2"))
	itemlist.append(Item("Sleep Seed", "Sleep", "Seeds", "seed", "Item_image_SEED_SLEEP"))
	itemlist.append(Item("Stun Seed", "Stun", "Seeds", "seed", "Item_image_SEED_KOUCHOKU"))
	itemlist.append(Item("Tiny Reviver Seed", "Tiny Reviver", "Seeds", "seed", "Item_image_SEED_FUKKATSU"))
	itemlist.append(Item("Totter Seed", "Totter", "Seeds", "seed", "Item_image_SEED_CONFUSE"))
	itemlist.append(Item("Training Seed", "Training", "Seeds", "seed", "Item_image_SEED_TANREN"))
	itemlist.append(Item("Violent Seed", "Violent", "Seeds", "seed", "Item_image_SEED_MOUGEKI"))
	itemlist.append(Item("Warp Seed", "Warp", "Seeds", "seed", "Item_image_SEED_WARP"))

	# Wands
	itemlist.append(Item("Confuse Wand", "Confuse", "Wand", "wand", "Item_image_WAND_KONRAN"))
	itemlist.append(Item("Guiding Wand", "Guiding", "Wand", "wand", "Item_image_WAND_GUIDE"))
	itemlist.append(Item("HP-Swap Wand", "HP-Swap", "Wand", "wand", "Item_image_WAND_HPGAE"))
	itemlist.append(Item("Petrify Wand", "Petrify", "Wand", "wand", "Item_image_WAND_SHIBARI"))
	itemlist.append(Item("Pounce Wand", "Pounce", "Wand", "wand", "Item_image_WAND_TOBITSUKI"))
	itemlist.append(Item("Slow Wand", "Slow", "Wand", "wand", "Item_image_WAND_DONSOKU"))
	itemlist.append(Item("Slumber Wand", "Slumber", "Wand", "wand", "Item_image_WAND_SUIMIN"))
	itemlist.append(Item("Stayaway Wand", "Stayaway", "Wand", "wand", "Item_image_WAND_SHINOGI"))
	itemlist.append(Item("Surround Wand", "Surround", "Wand", "wand", "Item_image_WAND_HOUI"))
	itemlist.append(Item("Switcher Wand", "Switcher", "Wand", "wand", "Item_image_WAND_BASHOGAE"))
	itemlist.append(Item("Tunnel Wand", "Tunnel", "Wand", "wand", "Item_image_WAND_TUNNEL"))
	itemlist.append(Item("Two-Edged Wand", "Two-Edged", "Wand", "wand", "Item_image_WAND_MOROHA"))
	itemlist.append(Item("Warp Wand", "Warp", "Wand", "wand", "Item_image_WAND_WARP"))
	itemlist.append(Item("Whirlwind Wand", "Whirlwind", "Wand", "wand", "Item_image_WAND_FUKITOBASHI"))

	# Orbs
	itemlist.append(Item("All Dodge Orb", "All Dodge", "Orb", "orb", "Item_image_ORB_KAIHI"))
	itemlist.append(Item("All Power-Up Orb", "All Power-Up", "Orb", "orb", "Item_image_ORB_POWERUP"))
	itemlist.append(Item("All Protect Orb", "All Protect", "Orb", "orb", "Item_image_ORB_MINNAMUTEKI"))
	itemlist.append(Item("Bank Orb", "Bank", "Orb", "orb", "Item_image_ORB_PERUSHIAN"))
	itemlist.append(Item("Cleanse Orb", "Cleanse", "Orb", "orb", "Item_image_ORB_SENTAKU"))
	itemlist.append(Item("Decoy Orb", "Decoy", "Orb", "orb", "Item_image_ORB_CHUUMOKU"))
	itemlist.append(Item("Drought Orb", "Drought", "Orb", "orb", "Item_image_ORB_HIAGARI"))
	itemlist.append(Item("Escape Orb", "Escape", "Orb", "orb", "Item_image_ORB_ANANUKE"))
	itemlist.append(Item("Evasion Orb", "Evasion", "Orb", "orb", "Item_image_ORB_BUNSHIN"))
	itemlist.append(Item("Foe-Hold Orb", "Foe-Hold", "Orb", "orb", "Item_image_ORB_TEKISHIBARI"))
	itemlist.append(Item("Foe-Seal Orb", "Foe-Seal", "Orb", "orb", "Item_image_ORB_TEKIFUUJI"))
	itemlist.append(Item("Hail Orb", "Hail", "Orb", "orb", "Item_image_ORB_ARARE"))
	itemlist.append(Item("Health Orb", "Health", "Orb", "orb", "Item_image_ORB_KENKOU"))
	itemlist.append(Item("Helper Orb", "Helper", "Orb", "orb", "Item_image_ORB_HELPER"))
	itemlist.append(Item("Inviting Orb", "Inviting", "Orb", "orb", "Item_image_ORB_INVITATION"))
	itemlist.append(Item("Lasso Orb", "Lasso", "Orb", "orb", "Item_image_ORB_KUGIZUKE"))
	itemlist.append(Item("Luminous Orb", "Luminous", "Orb", "orb", "Item_image_ORB_HIKARI"))
	itemlist.append(Item("Mobile Orb", "Mobile", "Orb", "orb", "Item_image_ORB_TSUUKA"))
	itemlist.append(Item("Monster Orb", "Monster", "Orb", "orb", "Item_image_ORB_MONSTERHOUSE"))
	itemlist.append(Item("Nullify Orb", "Nullify", "Orb", "orb", "Item_image_ORB_TOKUSEIKESHI"))
	itemlist.append(Item("One-Room Orb", "One-Room", "Orb", "orb", "Item_image_ORB_OOBEYA"))
	itemlist.append(Item("One-Shot Orb", "One-Shot", "Orb", "orb", "Item_image_ORB_ICHIGEKI"))
	itemlist.append(Item("Petrify Orb", "Petrify", "Orb", "orb", "Item_image_ORB_SHIBARI"))
	itemlist.append(Item("Quick Orb", "Quick", "Orb", "orb", "Item_image_ORB_SHUNSOKU"))
	itemlist.append(Item("Radar Orb", "Radar", "Orb", "orb", "Item_image_ORB_HIDERI"))
	itemlist.append(Item("Rainy Orb", "Rainy", "Orb", "orb", "Item_image_ORB_AME"))
	itemlist.append(Item("Rare Quality Orb", "Rare Quality", "Orb", "orb", "Item_image_ORB_SUGOWAZA"))
	itemlist.append(Item("Reset Orb", "Reset", "Orb", "orb", "Item_image_ORB_RESET"))
	itemlist.append(Item("Revive All Orb", "Revive All", "Orb", "orb", "Item_image_ORB_NEKTAR"))
	itemlist.append(Item("Rollcall Orb", "Rollcall", "Orb", "orb", "Item_image_ORB_ATSUMARE"))
	itemlist.append(Item("Sandy Orb", "Sandy", "Orb", "orb", "Item_image_ORB_SUNA"))
	itemlist.append(Item("Scanner Orb", "Scanner", "Orb", "orb", "Item_image_ORB_MONOMI"))
	itemlist.append(Item("See-Trap Orb", "See-Trap", "Orb", "orb", "Item_image_ORB_WANAMIE"))
	itemlist.append(Item("Slow Orb", "Slow", "Orb", "orb", "Item_image_ORB_DONSOKU"))
	itemlist.append(Item("Slumber Orb", "Slumber", "Orb", "orb", "Item_image_ORB_BAKUSUI"))
	itemlist.append(Item("Spurn Orb", "Spurn", "Orb", "orb", "Item_image_ORB_HARAINOKE"))
	itemlist.append(Item("Storage Orb", "Storage", "Orb", "orb", "Item_image_ORB_SOUKO"))
	itemlist.append(Item("Sunny Orb", "Sunny", "Orb", "orb", "Item_image_ORB_ATSUMARE"))
	itemlist.append(Item("Totter Orb", "Totter", "Orb", "orb", "Item_image_ORB_FURAFURA"))
	itemlist.append(Item("Trapbust Orb", "Trapbust", "Orb", "orb", "Item_image_ORB_WANAKOWASHI"))
	itemlist.append(Item("Trawl Orb", "Trawl", "Orb", "orb", "Item_image_ORB_HIKIYOSE"))
	itemlist.append(Item("Weather Lock Orb", "Weather Lock", "Orb", "orb", "Item_image_ORB_WEATHER_RESET"))
	itemlist.append(Item("Wigglytuff Orb", "Wigglytuff", "Orb", "orb", "Item_image_ORB_PUKURIN"))

	# Held Items
	itemlist.append(Item("Big Eater Belt", "Big Eater Belt", "Held Items", "band", "Item_image_EQUIP_OOGUI"))
	itemlist.append(Item("Cover Band", "Cover Band", "Held Items", "band", "Item_image_EQUIP_KABAI"))
	itemlist.append(Item("Defense Scarf", "Defense Scarf", "Held Items", "band", "Item_image_EQUIP_BOUGYO"))
	itemlist.append(Item("Deluxe Ribbon", "Deluxe Ribbon", "Held Items", "goldband", "Item_image_EQUIP_NORMAL"))
	itemlist.append(Item("Detect Band", "Detect Band", "Held Items", "band", "Item_image_EQUIP_MIKIRI"))
	itemlist.append(Item("Efficient Bandanna", "Efficient Bandanna", "Held Items", "band", "Item_image_EQUIP_SETSUYAKU"))
	itemlist.append(Item("Explosive Band", "Explosive Band", "Held Items", "band", "Item_image_EQUIP_KIKEN"))
	itemlist.append(Item("Fickle Specs", "Fickle Specs", "Held Items", "glasses", "Item_image_EQUIP_MEUTSURI"))
	itemlist.append(Item("Fierce Bandanna", "Fierce Bandanna", "Held Items", "band", "Item_image_EQUIP_IRYOKU"))
	itemlist.append(Item("Friend Bow", "Friend Bow", "Held Items", "band", "Item_image_EQUIP_FRIEND"))
	itemlist.append(Item("Gold Ribbon", "Gold Ribbon", "Held Items", "goldband", "Item_image_EQUIP_GOLD"))
	itemlist.append(Item("Goggle Specs", "Goggle Specs", "Held Items", "glasses", "Item_image_EQUIP_MEGUSURI"))
	itemlist.append(Item("Heal Ribbon", "Heal Ribbon", "Held Items", "band", "Item_image_EQUIP_HEAL"))
	itemlist.append(Item("Heavy Rotation Specs", "Heavy Rotation Specs", "Held Items", "glasses", "Item_image_EQUIP_HITOSUJI"))
	itemlist.append(Item("Insomniscope", "Insomniscope", "Held Items", "glasses", "Item_image_EQUIP_SLEEP"))
	itemlist.append(Item("Joy Ribbon", "Joy Ribbon", "Held Items", "band", "Item_image_EQUIP_HAPPY"))
	itemlist.append(Item("Lock-On Specs", "Lock-On Specs", "Held Items", "glasses", "Item_image_EQUIP_ROCKON"))
	itemlist.append(Item("Lucky Ribbon", "Lucky Ribbon", "Held Items", "band", "Item_image_EQUIP_OMAJINAI"))
	itemlist.append(Item("Mach Ribbon", "Mach Ribbon", "Held Items", "band", "Item_image_EQUIP_SUBAYASA"))
	itemlist.append(Item("Mobile Scarf", "Mobile Scarf", "Held Items", "band", "Item_image_EQUIP_THROUGH"))
	itemlist.append(Item("Munch Belt", "Munch Belt", "Held Items", "band", "Item_image_EQUIP_GONBE"))
	itemlist.append(Item("No-Stick Cap", "No-Stick Cap", "Held Items", "band", "Item_image_EQUIP_CURSE"))
	itemlist.append(Item("Nullify Bandanna", "Nullify Bandanna", "Held Items", "band", "Item_image_EQUIP_MUTOKUSEI"))
	itemlist.append(Item("Pass Scarf", "Pass Scarf", "Held Items", "band", "Item_image_EQUIP_UKENAGASI"))
	itemlist.append(Item("Pecha Scarf", "Pecha Scarf", "Held Items", "band", "Item_image_EQUIP_POISON"))
	itemlist.append(Item("Persim Band", "Persim Band", "Held Items", "band", "Item_image_EQUIP_CONFUSE"))
	itemlist.append(Item("Phase Ribbon", "Phase Ribbon", "Held Items", "band", "Item_image_EQUIP_DOKOMADE"))
	itemlist.append(Item("Pierce Band", "Pierce Band", "Held Items", "band", "Item_image_EQUIP_KANTSU"))
	itemlist.append(Item("Power Band", "Power Band", "Held Items", "band", "Item_image_EQUIP_KOUGEKI"))
	itemlist.append(Item("Prosper Ribbon", "Prosper Ribbon", "Held Items", "band", "Item_image_EQUIP_POKE"))
	itemlist.append(Item("Recovery Scarf", "Recovery Scarf", "Held Items", "band", "Item_image_EQUIP_IYASHI"))
	itemlist.append(Item("Reunion Cape", "Reunion Cape", "Held Items", "band", "Item_image_EQUIP_GOURYUU"))
	itemlist.append(Item("Scope Lens", "Scope Lens", "Held Items", "glasses", "Item_image_EQUIP_KAISIN"))
	itemlist.append(Item("Sneak Scarf", "Sneak Scarf", "Held Items", "band", "Item_image_EQUIP_SNEAK"))
	itemlist.append(Item("Special Band", "Special Band", "Held Items", "band", "Item_image_EQUIP_TOKUKOU"))
	itemlist.append(Item("Stamina Band", "Stamina Band", "Held Items", "band", "Item_image_EQUIP_HARAMOCHI"))
	itemlist.append(Item("Tight Belt", "Tight Belt", "Held Items", "band", "Item_image_EQUIP_HARAHERAZU"))
	itemlist.append(Item("Trap Scarf", "Trap Scarf", "Held Items", "band", "Item_image_EQUIP_WANANUKE"))
	itemlist.append(Item("Twist Band", "Twist Band", "Held Items", "band", "Item_image_EQUIP_NEJIRI"))
	itemlist.append(Item("Warp Scarf", "Warp Scarf", "Held Items", "band", "Item_image_EQUIP_WARP"))
	itemlist.append(Item("Weather Band", "Weather Band", "Held Items", "band", "Item_image_EQUIP_WEATHER"))
	itemlist.append(Item("X-Ray Specs", "X-Ray Specs", "Held Items", "glasses", "Item_image_EQUIP_MITOOSHI"))
	itemlist.append(Item("Zinc Band", "Zinc Band", "Held Items", "band", "Item_image_EQUIP_TOKUBOU"))

	# TMs
	itemlist.append(Item("Acrobatics", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Aerial Ace", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Attract", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Aurora Veil", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Blizzard", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Brick Break", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Brutal Swing", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Bulk Up", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Bulldoze", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Calm Mind", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Charge Beam", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Confide", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Dark Pulse", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Dazzling Gleam", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Double Team", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Dragon Claw", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Dragon Tail", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Dream Eater", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Earthquake", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Echoed Voice", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Embargo", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Energy Ball", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Explosion", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Facade", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("False Swipe", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Fire Blast", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Flame Charge", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Flamethrower", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Flash Cannon", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Fling", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Fly", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Focus Blast", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Frost Breath", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Frustration", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Giga Impact", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Grass Knot", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Gyro Ball", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Hail", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Hidden Power", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Hyper Beam", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Ice Beam", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Infestation", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Leech Life", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Light Screen", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Low Sweep", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Nature Power", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Overheat", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Payback", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Poison Jab", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Protect", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Psych Up", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Psychic", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Psyshock", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Quash", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Rain Dance", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Reflect", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Rest", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Return", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Roar", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Rock Polish", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Rock Slide", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Rock Tomb", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Roost", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Round", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Safeguard", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Sandstorm", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Scald", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Shadow Ball", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Shadow Claw", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Sky Drop", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Sleep Talk", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Sludge Bomb", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Sludge Wave", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Smack Down", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Smart Strike", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Snarl", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Solar Beam", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Steel Wing", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Stone Edge", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Substitute", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Sunny Day", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Surf", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Swagger", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Swords Dance", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Taunt", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Thief", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Thunder", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Thunder Wave", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Thunderbolt", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Torment", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Toxic", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Trick Room", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("U-turn", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Venoshock", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Volt Switch", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Waterfall", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Wild Charge", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Will-O-Wisp", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("Work Up", "", "TMs", "tm", "Item_image_WAZAMACHINE"))
	itemlist.append(Item("X-Scissor", "", "TMs", "tm", "Item_image_WAZAMACHINE"))

	# Special
	itemlist.append(Item("Bronze Dojo Ticket", "Bronze Dojo Ticket", "Special", "ticket", "Item_image_OTHER_TRAINING_TICKET_A"))
	itemlist.append(Item("Silver Dojo Ticket", "Silver Dojo Ticket", "Special", "silverdojoticket", "Item_image_OTHER_TRAINING_TICKET_B"))
	itemlist.append(Item("Gold Dojo Ticket", "Gold Dojo Ticket", "Special", "golddojoticket", "Item_image_OTHER_TRAINING_TICKET_C"))
	itemlist.append(Item("Rainbow Gummi", "Rainbow Gummi", "Special", "rainbowgummi", "Item_image_PARAMETER_GUMI"))
	itemlist.append(Item("DX Gummi", "DX Gummi", "Special", "goldgummi", "Item_image_PARAMETER_GUMI_DX"))
	itemlist.append(Item("Pretty Box", "Pretty Box", "Special", "prettybox", "Item_image_CHEST_UTSUKUSHII_A"))
	itemlist.append(Item("Deluxe Box", "Deluxe Box", "Special", "box", "Item_image_CHEST_KAGAYAKU_A"))
	itemlist.append(Item("Evolution Crystal", "Evolution Crystal", "Special", "evolutioncrystal", "Item_image_EVOLUTION_COMMON"))
	itemlist.append(Item("Invitation", "Invitation", "Special", "invitation", "Item_image_OTHER_INVITATION"))
	itemlist.append(Item("Link Box", "Link Box", "Special", "linkbox", "Item_image_BOX_RENKETSU"))

	return itemlist

# Returns a list of filenames (without the .txt) to look into.
# This is necessary since we don't necessarily want to scan every file in the repo
def getDungeons():
	dungeonlist = []
	dungeonlist.append("dungeon/Tiny Woods")
	dungeonlist.append("dungeon/Thunderwave Cave")
	dungeonlist.append("dungeon/Mt. Steel")
	dungeonlist.append("dungeon/Oddity Cave")
	dungeonlist.append("dungeon/Sinister Woods")
	dungeonlist.append("dungeon/Silent Chasm")
	dungeonlist.append("dungeon/Mt. Thunder")
	dungeonlist.append("dungeon/Mt. Thunder Peak")
	dungeonlist.append("dungeon/Great Canyon")
	dungeonlist.append("dungeon/Lapis Cave")
	dungeonlist.append("dungeon/Rock Path")
	dungeonlist.append("dungeon/Mt. Blaze")
	dungeonlist.append("dungeon/Mt. Blaze Peak")
	dungeonlist.append("dungeon/Frosty Forest")
	dungeonlist.append("dungeon/Heart of the Frosty Forest")
	dungeonlist.append("dungeon/Snow Path")
	dungeonlist.append("dungeon/Mt. Freeze")
	dungeonlist.append("dungeon/Mt. Freeze Peak")
	dungeonlist.append("dungeon/Uproar Forest")
	dungeonlist.append("dungeon/Magma Cavern")
	dungeonlist.append("dungeon/Magma Cavern Pit")
	dungeonlist.append("dungeon/Sky Tower")
	dungeonlist.append("dungeon/Sky Tower Summit")

	dungeonlist.append("dungeon/Waterfall Pond")
	dungeonlist.append("dungeon/Remains Island")
	dungeonlist.append("dungeon/Desert Region")
	dungeonlist.append("dungeon/Southern Cavern")
	dungeonlist.append("dungeon/Wyvern Hill")
	dungeonlist.append("dungeon/Darknight Relic")
	dungeonlist.append("dungeon/Unown Relic")
	dungeonlist.append("dungeon/Grand Sea")
	dungeonlist.append("dungeon/Far-Off Sea")

	dungeonlist.append("dungeon/Howling Forest")
	dungeonlist.append("dungeon/Stormy Sea")
	dungeonlist.append("dungeon/Buried Relic")
	dungeonlist.append("dungeon/Solar Cave")
	dungeonlist.append("dungeon/Fiery Field")
	dungeonlist.append("dungeon/Lightning Field")
	dungeonlist.append("dungeon/Northwind Field")
	dungeonlist.append("dungeon/Mt. Faraway")
	dungeonlist.append("dungeon/Western Cave")
	dungeonlist.append("dungeon/Northern Range")
	dungeonlist.append("dungeon/Pitfall Valley")
	dungeonlist.append("dungeon/Joyous Tower")
	dungeonlist.append("dungeon/Purity Forest")
	dungeonlist.append("dungeon/Wish Cave")
	dungeonlist.append("dungeon/Murky Cave")
	dungeonlist.append("dungeon/Silver Trench")
	dungeonlist.append("dungeon/Meteor Cave")
	dungeonlist.append("dungeon/Marvelous Sea")
	dungeonlist.append("dungeon/Fantasy Strait")
	
	# Non-dungeons with potentially hardwired inventories
	dungeonlist.append("other/Square - Kecleon Shop")
	dungeonlist.append("other/Square - Kecleon Wares")
	dungeonlist.append("other/Square - Felicity Bank")
	dungeonlist.append("other/Square - Mailbox")
	dungeonlist.append("other/Square - Munchlax")
	dungeonlist.append("other/Rescue - Pokémon Square")
	dungeonlist.append("other/Rescue - Regular")
	dungeonlist.append("other/Rescue - Special")
	dungeonlist.append("other/Rescue - Deluxe")

	dungeonlist.append("other/Box - Pretty Box")
	dungeonlist.append("other/Box - Deluxe Box")
	
	return dungeonlist

# Returns the item object based on the FULL NAME. Drop name is insufficient due to some items having the same drop name (e.g. Totter Seed and Totter Orb)
# Intended use is mapping text in the drop logs to the item objects
def getItemByName(name, itemlist):
	for item in itemlist:
		if item.name == name:
			return item
	print("Unable to find item " + name + " in item list")
	return None
	
